package com.estampate.corteI.hibernate;
// Generated 3/09/2015 11:13:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Artista generated by hbm2java
 */
public class Artista  implements java.io.Serializable {


     private Integer idArtista;
     private String nombre;
     private String apellido;
     private String direccion;
     private String cedula;
     private String celular;
     private String usuario;
     private String password;
     private Set<EstampaCamiseta> estampaCamisetas = new HashSet<EstampaCamiseta>(0);

    public Artista() {
    }

    public Artista(String nombre, String apellido, String direccion, String cedula, String celular, String usuario, String password, Set<EstampaCamiseta> estampaCamisetas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.cedula = cedula;
       this.celular = celular;
       this.usuario = usuario;
       this.password = password;
       this.estampaCamisetas = estampaCamisetas;
    }
   
    public Integer getIdArtista() {
        return this.idArtista;
    }
    
    public void setIdArtista(Integer idArtista) {
        this.idArtista = idArtista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<EstampaCamiseta> getEstampaCamisetas() {
        return this.estampaCamisetas;
    }
    
    public void setEstampaCamisetas(Set<EstampaCamiseta> estampaCamisetas) {
        this.estampaCamisetas = estampaCamisetas;
    }




}


