package com.estampate.corteI.hibernate;
// Generated 2/09/2015 08:09:47 PM by Hibernate Tools 4.3.1



/**
 * Artista generated by hbm2java
 */
public class Artista  implements java.io.Serializable {


     private Integer idArtista;
     private String nombre;
     private String apellido;
     private String direccion;
     private Integer cedula;
     private Integer celular;
     private String usuario;
     private String password;

    public Artista() {
    }

    public Artista(String nombre, String apellido, String direccion, Integer cedula, Integer celular, String usuario, String password) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.cedula = cedula;
       this.celular = celular;
       this.usuario = usuario;
       this.password = password;
    }
   
    public Integer getIdArtista() {
        return this.idArtista;
    }
    
    public void setIdArtista(Integer idArtista) {
        this.idArtista = idArtista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCedula() {
        return this.cedula;
    }
    
    public void setCedula(Integer cedula) {
        this.cedula = cedula;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


