package com.estampate.corteI.hibernate;
// Generated 2/09/2015 10:57:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ColorCamiseta generated by hbm2java
 */
public class ColorCamiseta  implements java.io.Serializable {


     private Integer idColor;
     private String color;
     private Set<Camiseta> camisetas = new HashSet<Camiseta>(0);
     private Set<FacturaDetalle> facturaDetalles = new HashSet<FacturaDetalle>(0);

    public ColorCamiseta() {
    }

	
    public ColorCamiseta(String color) {
        this.color = color;
    }
    public ColorCamiseta(String color, Set<Camiseta> camisetas, Set<FacturaDetalle> facturaDetalles) {
       this.color = color;
       this.camisetas = camisetas;
       this.facturaDetalles = facturaDetalles;
    }
   
    public Integer getIdColor() {
        return this.idColor;
    }
    
    public void setIdColor(Integer idColor) {
        this.idColor = idColor;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set<Camiseta> getCamisetas() {
        return this.camisetas;
    }
    
    public void setCamisetas(Set<Camiseta> camisetas) {
        this.camisetas = camisetas;
    }
    public Set<FacturaDetalle> getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set<FacturaDetalle> facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


