package com.estampate.corteI.hibernate;
// Generated 3/09/2015 11:13:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MaterialCamiseta generated by hbm2java
 */
public class MaterialCamiseta  implements java.io.Serializable {


     private Integer idMaterial;
     private String material;
     private Set<Camiseta> camisetas = new HashSet<Camiseta>(0);
     private Set<FacturaDetalle> facturaDetalles = new HashSet<FacturaDetalle>(0);

    public MaterialCamiseta() {
    }

	
    public MaterialCamiseta(String material) {
        this.material = material;
    }
    public MaterialCamiseta(String material, Set<Camiseta> camisetas, Set<FacturaDetalle> facturaDetalles) {
       this.material = material;
       this.camisetas = camisetas;
       this.facturaDetalles = facturaDetalles;
    }
   
    public Integer getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(Integer idMaterial) {
        this.idMaterial = idMaterial;
    }
    public String getMaterial() {
        return this.material;
    }
    
    public void setMaterial(String material) {
        this.material = material;
    }
    public Set<Camiseta> getCamisetas() {
        return this.camisetas;
    }
    
    public void setCamisetas(Set<Camiseta> camisetas) {
        this.camisetas = camisetas;
    }
    public Set<FacturaDetalle> getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set<FacturaDetalle> facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


