package com.estampate.corteI.hibernate;
// Generated 3/09/2015 11:13:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PrecioTexto generated by hbm2java
 */
public class PrecioTexto  implements java.io.Serializable {


     private Integer idPrecioTexto;
     private String precio;
     private Set<FacturaDetalle> facturaDetalles = new HashSet<FacturaDetalle>(0);
     private Set<TamanoTexto> tamanoTextos = new HashSet<TamanoTexto>(0);

    public PrecioTexto() {
    }

	
    public PrecioTexto(String precio) {
        this.precio = precio;
    }
    public PrecioTexto(String precio, Set<FacturaDetalle> facturaDetalles, Set<TamanoTexto> tamanoTextos) {
       this.precio = precio;
       this.facturaDetalles = facturaDetalles;
       this.tamanoTextos = tamanoTextos;
    }
   
    public Integer getIdPrecioTexto() {
        return this.idPrecioTexto;
    }
    
    public void setIdPrecioTexto(Integer idPrecioTexto) {
        this.idPrecioTexto = idPrecioTexto;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public Set<FacturaDetalle> getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set<FacturaDetalle> facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }
    public Set<TamanoTexto> getTamanoTextos() {
        return this.tamanoTextos;
    }
    
    public void setTamanoTextos(Set<TamanoTexto> tamanoTextos) {
        this.tamanoTextos = tamanoTextos;
    }




}


