package com.estampate.corteI.hibernate;
// Generated 2/09/2015 08:09:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RatingEstampa generated by hbm2java
 */
public class RatingEstampa  implements java.io.Serializable {


     private Integer idRatingEstampa;
     private String nombre;
     private Set<EstampaCamiseta> estampaCamisetas = new HashSet<EstampaCamiseta>(0);

    public RatingEstampa() {
    }

	
    public RatingEstampa(String nombre) {
        this.nombre = nombre;
    }
    public RatingEstampa(String nombre, Set<EstampaCamiseta> estampaCamisetas) {
       this.nombre = nombre;
       this.estampaCamisetas = estampaCamisetas;
    }
   
    public Integer getIdRatingEstampa() {
        return this.idRatingEstampa;
    }
    
    public void setIdRatingEstampa(Integer idRatingEstampa) {
        this.idRatingEstampa = idRatingEstampa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<EstampaCamiseta> getEstampaCamisetas() {
        return this.estampaCamisetas;
    }
    
    public void setEstampaCamisetas(Set<EstampaCamiseta> estampaCamisetas) {
        this.estampaCamisetas = estampaCamisetas;
    }




}


