package com.estampate.corteI.hibernate;
// Generated 2/09/2015 08:09:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TamanoTexto generated by hbm2java
 */
public class TamanoTexto  implements java.io.Serializable {


     private Integer idTamanoTexto;
     private PrecioTexto precioTexto;
     private String especificacionTamano;
     private Set<TextoCamiseta> textoCamisetas = new HashSet<TextoCamiseta>(0);
     private Set<FacturaDetalle> facturaDetalles = new HashSet<FacturaDetalle>(0);

    public TamanoTexto() {
    }

	
    public TamanoTexto(PrecioTexto precioTexto, String especificacionTamano) {
        this.precioTexto = precioTexto;
        this.especificacionTamano = especificacionTamano;
    }
    public TamanoTexto(PrecioTexto precioTexto, String especificacionTamano, Set<TextoCamiseta> textoCamisetas, Set<FacturaDetalle> facturaDetalles) {
       this.precioTexto = precioTexto;
       this.especificacionTamano = especificacionTamano;
       this.textoCamisetas = textoCamisetas;
       this.facturaDetalles = facturaDetalles;
    }
   
    public Integer getIdTamanoTexto() {
        return this.idTamanoTexto;
    }
    
    public void setIdTamanoTexto(Integer idTamanoTexto) {
        this.idTamanoTexto = idTamanoTexto;
    }
    public PrecioTexto getPrecioTexto() {
        return this.precioTexto;
    }
    
    public void setPrecioTexto(PrecioTexto precioTexto) {
        this.precioTexto = precioTexto;
    }
    public String getEspecificacionTamano() {
        return this.especificacionTamano;
    }
    
    public void setEspecificacionTamano(String especificacionTamano) {
        this.especificacionTamano = especificacionTamano;
    }
    public Set<TextoCamiseta> getTextoCamisetas() {
        return this.textoCamisetas;
    }
    
    public void setTextoCamisetas(Set<TextoCamiseta> textoCamisetas) {
        this.textoCamisetas = textoCamisetas;
    }
    public Set<FacturaDetalle> getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set<FacturaDetalle> facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


