package com.estampate.corteI.hibernate;
// Generated 3/09/2015 11:13:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TamanoEstampa generated by hbm2java
 */
public class TamanoEstampa  implements java.io.Serializable {


     private Integer idTamanoEstampa;
     private PrecioEstampa precioEstampa;
     private String especificacionTamano;
     private Set<FacturaDetalle> facturaDetalles = new HashSet<FacturaDetalle>(0);
     private Set<EstampaCamiseta> estampaCamisetas = new HashSet<EstampaCamiseta>(0);

    public TamanoEstampa() {
    }

	
    public TamanoEstampa(PrecioEstampa precioEstampa, String especificacionTamano) {
        this.precioEstampa = precioEstampa;
        this.especificacionTamano = especificacionTamano;
    }
    public TamanoEstampa(PrecioEstampa precioEstampa, String especificacionTamano, Set<FacturaDetalle> facturaDetalles, Set<EstampaCamiseta> estampaCamisetas) {
       this.precioEstampa = precioEstampa;
       this.especificacionTamano = especificacionTamano;
       this.facturaDetalles = facturaDetalles;
       this.estampaCamisetas = estampaCamisetas;
    }
   
    public Integer getIdTamanoEstampa() {
        return this.idTamanoEstampa;
    }
    
    public void setIdTamanoEstampa(Integer idTamanoEstampa) {
        this.idTamanoEstampa = idTamanoEstampa;
    }
    public PrecioEstampa getPrecioEstampa() {
        return this.precioEstampa;
    }
    
    public void setPrecioEstampa(PrecioEstampa precioEstampa) {
        this.precioEstampa = precioEstampa;
    }
    public String getEspecificacionTamano() {
        return this.especificacionTamano;
    }
    
    public void setEspecificacionTamano(String especificacionTamano) {
        this.especificacionTamano = especificacionTamano;
    }
    public Set<FacturaDetalle> getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set<FacturaDetalle> facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }
    public Set<EstampaCamiseta> getEstampaCamisetas() {
        return this.estampaCamisetas;
    }
    
    public void setEstampaCamisetas(Set<EstampaCamiseta> estampaCamisetas) {
        this.estampaCamisetas = estampaCamisetas;
    }




}


