package com.estampate.corteI.hibernate;
// Generated 2/09/2015 10:57:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TemaEstampa generated by hbm2java
 */
public class TemaEstampa  implements java.io.Serializable {


     private Integer idTemaEstampa;
     private String tipoTema;
     private Set<FacturaDetalle> facturaDetalles = new HashSet<FacturaDetalle>(0);
     private Set<EstampaCamiseta> estampaCamisetas = new HashSet<EstampaCamiseta>(0);

    public TemaEstampa() {
    }

	
    public TemaEstampa(String tipoTema) {
        this.tipoTema = tipoTema;
    }
    public TemaEstampa(String tipoTema, Set<FacturaDetalle> facturaDetalles, Set<EstampaCamiseta> estampaCamisetas) {
       this.tipoTema = tipoTema;
       this.facturaDetalles = facturaDetalles;
       this.estampaCamisetas = estampaCamisetas;
    }
   
    public Integer getIdTemaEstampa() {
        return this.idTemaEstampa;
    }
    
    public void setIdTemaEstampa(Integer idTemaEstampa) {
        this.idTemaEstampa = idTemaEstampa;
    }
    public String getTipoTema() {
        return this.tipoTema;
    }
    
    public void setTipoTema(String tipoTema) {
        this.tipoTema = tipoTema;
    }
    public Set<FacturaDetalle> getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set<FacturaDetalle> facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }
    public Set<EstampaCamiseta> getEstampaCamisetas() {
        return this.estampaCamisetas;
    }
    
    public void setEstampaCamisetas(Set<EstampaCamiseta> estampaCamisetas) {
        this.estampaCamisetas = estampaCamisetas;
    }




}


